/// Flutter icons Vmticons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Vmticons
///      fonts:
///       - asset: fonts/Vmticons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Icomoon {
  Icomoon._();

  static const String _kFontFam = 'icomoon';
  static const String? _kFontPkg = null;

  static const IconData vmtring =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vmtlogo =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pacman = IconData(0xe916, fontFamily: _kFontFam);
  static const IconData fire =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
